---
- name: check if file already exists
  stat:
    path: /tmp/encryption-config.yml
  register: encryptionConfig

- name: generate an encryption key
  shell: head -c 32 /dev/urandom | base64
  delegate_to: "{{ groups['kube-masters'][0] }}"
  run_once: true
  when: not encryptionConfig.stat.exists
  register: command_output

- set_fact:
    encryption_key: "{{ command_output.stdout }}"
  when: not encryptionConfig.stat.exists

- name: copy the encryption config to all master nodes
  template:
    src: encryption-config.yml.j2
    dest: /tmp/encryption-config.yml
  when: not encryptionConfig.stat.exists
